### PR TITLE
 Igor Buga - Planable qa task

### PR DESCRIPTION
**Pull request by IgoriVic**

### CODE REVIEW

**Comment by tommy-anderson** [comment]
Hey Igor, I mistakenly wrote in the ReadMe to open the PR in this repo. Instead can I please ask you to open your PR in the private repo so that I can write feedback there :).

**Comment by IgoriVic** [comment]
> Owner

Hello Alex. I am ssory, did not see that message. Sure I wiil do that.

**Comment by IgoriVic** [comment]
> Hey Igor, I mistakenly wrote in the ReadMe to open the PR in this repo. Instead can I please ask you to open your PR in the private repo so that I can write feedback there :).

So as asked, I created a private repo and created a PR for review. Please accept the invitation and take a look at the open PR. Thanks in advance!

https://github.com/IgoriVic/planable-qa-task-winter-2023-private/pull/1

**Comment by tommy-anderson** [comment]
I will leave feedback soon ! Closing this PR

**Pull request closed without merging**
